### PR TITLE
PR251

### PR DESCRIPTION
**Pull request by padsley**
Merge of updated gamma-ray algorithms from the PR251 branch into the master, as requested by the Great Big Boss @neveling.

I'll do the merge but @pellegri and @neveling should approve.

### CODE REVIEW

**Comment by padsley** [comment]
Getting some compilation errors resulting from experim.h.

Might need you to pitch in to fix them, @neveling. If I can't, I'll push my changes and let you deal with it. :D

**Comment by padsley** [comment]
I don't want to delete this branch...

**Comment by padsley** [comment]
This is the problem:

```
padsley@padsley2016:~/codes/k600analysertmp$ make
g++  -pthread -m64 -I/home/padsley/codes/root/include -DHAVE_ROOT -DUSE_ROOT -Wno-cpp -lrt -O2 -g -I/home/padsley/codes/midas/midas/include -I/home/padsley/codes/midas/midas/drivers/vme/vmic -I/home/padsley/codes/midas/midas/drivers/vme -I/home/padsley/codes/midas/midas/drivers/vme -DOS_LINUX -Dextname -o analyzer.o -c analyzer.c
In file included from analyzer.c:18:0:
experim.h:2361:0: warning: "BEAMLINE_COMMON_STR" redefined
 #define BEAMLINE_COMMON_STR(_name) char *_name[] = {\
 ^
experim.h:227:0: note: this is the location of the previous definition
 #define BEAMLINE_COMMON_STR(_name) char*_name[] = {\
 ^
experim.h:2359:3: error: conflicting declaration ‘typedef struct BEAMLINE_COMMON BEAMLINE_COMMON’
 } BEAMLINE_COMMON;
   ^
experim.h:225:3: note: previous declaration as ‘typedef struct BEAMLINE_COMMON BEAMLINE_COMMON’
 } BEAMLINE_COMMON;
```

**Comment by pellegri** [comment]
Hey Phil,

thanks! Can you please don’t remove or change the PR251 I would like to keep this version for my analysis and modifying it to include the future changes for the Gamma branch. ok?
At which status is the merging now? Problem with the experiment.h? Should I do something?

Cheers,
Luna

**Comment by neveling** [comment]
At last, Slacker Neveling is reading his email and doing his bit.

This problem
"experim.h:2361:0: warning: "BEAMLINE_COMMON_STR" redefined..."
I did not experience.

There was some basic ODB size mismatch issues, which was fixed by creating a new experim.h file.

After I pulled the latest down to my laptop, both the PR251 and master branches compile.

**Pull request merged**
