### PR TITLE
PR238_2016 into PR264 for the porpoises of using the scintillators

### PR DESCRIPTION
**Pull request by padsley**

### CODE REVIEW

**Comment by padsley** [comment]
Just for my reference: 

Auto-merging main.c
CONFLICT (content): Merge conflict in main.c
Auto-merging basic.odb
CONFLICT (content): Merge conflict in basic.odb
Auto-merging Makefile
CONFLICT (content): Merge conflict in Makefile
Automatic merge failed; fix conflicts and then commit the result.

**Comment by padsley** [comment]
Done. Can someone test this?

**Comment by padsley** [comment]
Wait. There's an error. Looking into it.

**Comment by pellegri** [comment]
Error???

**Comment by padsley** [comment]
For reference: the problem was that beamline.o was not included in the Makefile because I'm a numpty who can't read. Now fixed.

**Pull request merged**
